#!/usr/bin/env python
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as optimize
from scipy.interpolate import interp1d
import collections
from eos_mod import MGD_PowerLaw,debye_fun,Ptot_powerlaw,press_vinet
from eval_Pt_eos_clean import rho_to_vol


#read file
p_dic = dict()
dat = np.loadtxt(fname='Table4-Pt.md', delimiter='|', skiprows=1)
#print dat
t = dat[0,1:]*1000 #unit K
print t
v0 = rho_to_vol(21.472) #unit grams/cm3 -> unit Ang^3/unitcell
v = dat[1:,0]*v0 #unit Ang^3/unitcell
print v
P_PowerLaw = MGD_PowerLaw(v, t, )